name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Test tests.php
      uses: fjogeleit/http-request-action@v1
      with:
        url: "${{ secrets.url }}/tests.php"
        method: 'GET'
        customHeaders: '{"Authorization": "${{ secrets.token }}"}'
        expectedStatus: 200
        # the response is a json, check if the key responsecode is 200
        expectedResponse: '{"responsecode": 200}'
        # else the test fails
        failOnError: true
