name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Send GET Request
        run: |
          URL=${{ secrets.url }}
          RESPONSE=$(curl -s -H "Accept: application/json" -H "Authorization: ${{ secrets.token }}" $URL)
          echo "Response from $URL: $RESPONSE"
          echo "::set-output name=response::$RESPONSE"

      - name: Check JSON Response
        id: check
        run: |
          RESPONSE_CODE=$(echo ${{ steps.send_get_request.outputs.response }} | jq -r '.responsecode')
          if [ "$RESPONSE_CODE" == "200" ]; then
            echo "Response code is 200"
          else
            echo "Response code is : $RESPONSE_CODE"
            echo "Response body is : ${{ steps.send_get_request.outputs.response }}"
            exit 1
          fi
        env:
          API_URL: ${{ secrets.url }}
