name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_response:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Send GET Request and check JSON Response
        run: |
          URL=${{ secrets.url }}/tests.php
          RESPONSE=$(curl -s -H "Accept: application/json" -H "Authorization: ${{ secrets.token }}" $URL)
          RESPONSE_CODE=$(echo $RESPONSE | jq -r '.responsecode')
          if [ "$RESPONSE_CODE" == "200" ]; then
            echo "Response code is 200"
          else
            echo "Response code is : $RESPONSE_CODE"
            echo "Response body is : $RESPONSE"
            exit 1
          fi
        env:
          API_URL: ${{ secrets.url }}
