name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_insertion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Send POST Request and check JSON Response
        run: |
          INDEX="{\"name\":\"test_gh\",\"numberframe\":\"2\",\"datetime\",\"2023-01-01 01:01:01\"}"
          CONTENT="{\"packets\":{\"0\":{\"packetid\":0,\"macsrc\":\"3c:22:fb:00:00:00\",\"ipsrc\":\"172.16.0.1\",\"ipdst\":\"192.168.1.1\",\"datapackets\":{\"tcp\":{\"dstport\":\"443\",\"srcport\":\"80\"}},\"macdst\":\"d4:76:a0:00:00:00\",\"protocols\":[\"eth\",\"ethertype\",\"ip\",\"tcp\",\"tls\"]},\"1\":{\"packetid\":1,\"macsrc\":\"d4:76:a0:00:56:02\",\"ipsrc\":\"192.168.1.1\",\"ipdst\":\"172.16.0.1\",\"datapackets\":{\"tcp\":{\"dstport\":\"80\",\"srcport\":\"443\"}},\"macdst\":\"3c:22:fb:00:00:00\",\"protocols\":[\"eth\",\"ethertype\",\"ip\",\"tcp\"]}}}"
          URL=${{ secrets.url }}/insert.php
          RESPONSE=$(curl -s -H "Accept: application/json" -H "Authorization: ${{ secrets.token }}" -d "dataindex=$INDEX&datapackets=$CONTENT" $URL)
          RESPONSE_CODE=$(echo $RESPONSE | jq -r '.responsecode')
          if [ "$RESPONSE_CODE" == "200" ]; then
            echo "Response code is 200"
          else
            echo "Response code is : $RESPONSE_CODE"
            echo "Response body is : $RESPONSE"
            exit 1
          fi

  check_tests_list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Send GET Request and check JSON Response
        run: |
          URL=${{ secrets.url }}/tests.php
          RESPONSE=$(curl -s -H "Accept: application/json" -H "Authorization: ${{ secrets.token }}" $URL)
          RESPONSE_CODE=$(echo $RESPONSE | jq -r '.responsecode')
          if [ "$RESPONSE_CODE" == "200" ]; then
            echo "Response code is 200"
          else
            echo "Response code is : $RESPONSE_CODE"
            echo "Response body is : $RESPONSE"
            exit 1
          fi
        env:
          API_URL: ${{ secrets.url }}

  check_packetslist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Send GET Request and check JSON Response
        run: |
          URL=${{ secrets.url }}/packets.php
          RESPONSE=$(curl -s -H "Accept: application/json" -H "User-Agent: GH-Action" -H "Authorization: ${{ secrets.token }}" $URL)
          RESPONSE_CODE=$(echo $RESPONSE | jq -r '.responsecode')
          if [ "$RESPONSE_CODE" == "200" ]; then
            echo "Response code is 200"
            LASTPACKETID=$(echo $RESPONSE | jq -r '.data.fileid')
            echo "Last packet id is $LASTPACKETID"

            URL=${{ secrets.url }}/packets.php?fileid=$LASTPACKETID
            RESPONSE=$(curl -s -H "Accept: application/json" -H "Authorization: ${{ secrets.token }}" $URL)
            RESPONSE_CODE=$(echo $RESPONSE | jq -r '.responsecode')
            if [ "$RESPONSE_CODE" == "200" ]; then
              echo "Response code is 200"
            else
              echo "Response code is : $RESPONSE_CODE"
              echo "Response body is : $RESPONSE"
              exit 1
            fi            
          else
            echo "Response code is : $RESPONSE_CODE"
            echo "Response body is : $RESPONSE"
            exit 1
          fi
        env:
          API_URL: ${{ secrets.url }}